# Generated by Django 2.2.4 on 2019-08-24 08:32

from django.db import migrations
from phonenumbers import parse, is_valid_number


def transfer_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects\
                .exclude(owners_phonenumber__isnull=True)\
                .exclude(owners_phonenumber__exact="")

    for flat in flats:
        pure_number = parse(flat.owners_phonenumber, 'RU')
        if not is_valid_number(pure_number):
            continue
        flat.owner_phone_pure=pure_number
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20190824_1125'),
    ]

    operations = [
        migrations.RunPython(transfer_phone_numbers)
    ]
