# Generated by Django 2.2.4 on 2019-08-24 19:04

from django.db import migrations


def transfer_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    
    flats = Flat.objects.all()

    for flat in flats:
        owner = Owner(owner=flat.owner,
                      owner_phonenumber=flat.owners_phonenumber,
                      owner_phone_pure=flat.owner_phone_pure)
        owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [
        migrations.RunPython(transfer_owners)
    ]
