# Generated by Django 2.2.4 on 2019-08-24 19:18

from django.db import migrations


def add_flats_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    
    flats = Flat.objects.all()

    for flat in flats:
        owner = Owner.objects.get_or_create(owner_phonenumber=flat.owners_phonenumber)
        owner.owner_flats.add(flat)
        owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20190824_2204'),
    ]

    operations = [
        migrations.RunPython(add_flats_to_owners)
    ]
