# Generated by Django 2.2.4 on 2019-09-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20190824_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(null=True, verbose_name='Новостройка'),
        ),
    ]
