# Generated by Django 2.2.4 on 2019-09-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20190923_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='active',
            field=models.NullBooleanField(db_index=True, verbose_name='Активно-ли объявление'),
        ),
    ]
